Sprint 3
Tratori/DYOD_SoSe23 pull request #6
Opened 2023-05-30 20:08 UTC by Tratori

2023-05-31 21:10 UTC, rothaarlappen requested changes

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/get_table.cpp
> +  return storageManager.get_table(_table_name);
```suggestion
auto storageManager = &StorageManager::get();
  Assert(storageManager->has_table(_table_name), "Table " + _table_name + " does not exist");
  return storageManager->get_table(_table_name);
```

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +  auto const column_type = input_table->column_type(_column_id);
```suggestion
  const auto column_type = input_table->column_type(_column_id);
```

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +
Should we throw an error here, if none of the casts succeded?

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +  }
```suggestion
  for (auto index = ChunkOffset{0}; index < segment->size(); ++index) {
    const auto value_id = attr_vector->get(index); 
    if (scan_op(value_id, lower_bound)) {
      position_list->push_back(RowID{chunk_id, index});
    }
  }
```

maybe this is easier to understand than "value_ind" being not the value_id but the index...

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +
hidden

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +  }
```suggestion
  auto index = ChunkOffset{0};
  for (const auto& value : values) {
    if (scan_op(value, search_val)) {
      position_list->push_back(RowID{chunk_id, index});
    }
    ++index;
  }
```

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +    const auto target_segment = chunk->get_segment(_column_id);
does this need to happen inside the for-loop?

2023-05-31 21:10 UTC, rothaarlappen commented on src/lib/operators/table_scan.cpp
> +    const auto val_segment = std::dynamic_pointer_cast<ValueSegment<T>>(target_segment);
Also not sure if this needs to be executed in each iteration

2023-05-31 21:27 UTC, Tratori commented on src/lib/operators/table_scan.cpp
> +
yes

2023-05-31 21:29 UTC, Tratori commented on src/lib/operators/table_scan.cpp
> +  }
agree

2023-05-31 21:38 UTC, rrcomtech commented on src/lib/operators/table_scan.cpp
> +  }
Sounds reasonable 👍🏼

2023-05-31 21:56 UTC, rothaarlappen approved these changes

2023-06-03 17:01 UTC, kathrinthenhausen reviewed
🌻

2023-06-03 17:01 UTC, kathrinthenhausen commented on src/lib/operators/get_table.cpp
> +  Assert(storageManager->has_table(_table_name), "Table " + _table_name + " does not exist");
Nice, to make an assertion here 👍

2023-06-03 17:01 UTC, kathrinthenhausen commented on src/lib/storage/reference_segment.cpp
> +  DebugAssert(row_id.chunk_offset < segment->size(), "RowID offset is out of bounds");
why do you use DebugAssert instead of a normal Assert here?

2023-06-03 17:01 UTC, kathrinthenhausen commented on src/lib/storage/reference_segment.cpp
> +  const auto row_id = _pos_list->at(chunk_offset);
I would suggest an assertion before whether the given chunk_offset can be called in the pos list? 
```suggestion
  Assert(chunk_offset < _pos_list->size(), "Invalid offset given for chunk;
  const auto row_id = _pos_list->at(chunk_offset);
```

2023-06-03 17:01 UTC, kathrinthenhausen commented on src/lib/operators/table_scan.cpp
> +      if (lower_bound == upper_bound)
Nice use of the lambda functions :)

2023-06-03 17:01 UTC, kathrinthenhausen commented on src/lib/operators/table_scan.cpp
> +      }
You could do the cast in the if-statements like following:
```suggestion

      if (auto value_segment = std::dynamic_pointer_cast<ValueSegment<Type>>(segment); value_segment) {
        position_list = _tablescan_value_segment<Type>(value_segment, chunk_id);
      } else if ( auto dictionary_segment = std::dynamic_pointer_cast<DictionarySegment<Type>>(segment); dictionary_segment) {
        position_list = _tablescan_dict_segment<Type>(dictionary_segment, chunk_id);
      } else if (auto reference_segment = std::dynamic_pointer_cast<ReferenceSegment>(segment); reference_segment) {
        position_list = _tablescan_reference_segment<Type>(reference_segment, chunk_id);
      }
      else {
            Fail( "TableScan was called on unsupported segment type");
      }
```

2023-06-03 17:01 UTC, kathrinthenhausen reviewed
🌻

2023-06-05 14:18 UTC, Margarete01 reviewed
Generally very nice code. I like how you extracted the PositionList creation for the different segment types into different functions. Have another look if a type casts are really necessary.

2023-06-05 14:18 UTC, Margarete01 commented on src/lib/operators/abstract_operator.cpp
>  std::shared_ptr<const Table> AbstractOperator::get_output() const {
`_output` should be nullptr until the operator is executed, so you could `Assert(_output, ...)` instead of introducing another Boolean variable. Was there a specific reason behind your decision?

2023-06-05 14:18 UTC, Margarete01 commented on src/lib/operators/table_scan.cpp
> +
Here could be a nice spot to check whether the search value has the same type as your column as we don't want to compare different types with each other.
```suggestion
Assert(typeid(Type) == _search_value.type(), "Search value doesn't have the same type as the column, we want to compare it with.");
```

2023-06-05 14:18 UTC, Margarete01 commented on src/lib/operators/table_scan.cpp
> +      const auto casted_value = type_cast<T>(values[row.chunk_offset]);
Shouldn't the values of the ValueSegment already have `T` as type? Why are you type casting again?

2023-06-05 14:18 UTC, Margarete01 commented on src/lib/operators/table_scan.cpp
> +      const auto casted_value = type_cast<T>(value);
Same as above.

2023-06-05 14:18 UTC, Margarete01 commented on src/test/storage/reference_segment_test.cpp
> +  EXPECT_EQ(reference_segment.estimate_memory_usage(), 3 * 8);
3 and 8 seem like magic numbers. Maybe it's nicer to rewrite 8 as sizeOf(RowID)?

2023-06-05 14:58 UTC, Tratori commented on src/lib/operators/abstract_operator.cpp
>  std::shared_ptr<const Table> AbstractOperator::get_output() const {
No particular reason - that sounds like a good idea.

2023-06-10 21:54 UTC, merged